Bundle commons-io since gerrit core no longer provides it
By removing Solr from gerrit core in

  7fe1752bfdae0c280170ce2759146dc55bb6cd36

commons-io is no longer provided by the environment. Building this
plugin still worked, loading it still worked, but when using

  remoteNameStyle = basenameOnly

the plugin fails at runtime with

  [2015-07-30 11:44:04,171] WARN  org.eclipse.jetty.servlet.ServletHandler : Error for /projects/foo%2Fbar
  java.lang.NoClassDefFoundError: org/apache/commons/io/FilenameUtils
  [...]
  [2015-07-30 11:44:04,174] ERROR com.google.gerrit.pgm.http.jetty.HiddenErrorHandler : Error in PUT /projects/foo%2Fbar
  java.lang.NoClassDefFoundError: org/apache/commons/io/FilenameUtils

By moving commons-io to the explicit dependencies, the remoteNameStyle
basenameOnly works again.

Change-Id: Ifdfc54a3fceeb457cd4729da7568026a16cc0d22