Update patch set 8
Patch Set 8:

> Patch Set 8:
> 
> > Patch Set 8:
> > > Patch Set 8:
> > > > Patch Set 8:
> > > > > Patch Set 8:
> > > > > 
> > > > > Many errors like the following:
> > > > > 
> > > > > ERROR: /local/mnt/workspace/mfick/gerrit/gerrit.google2/plugins/replication/BUILD:5:1: Building plugins/replication/libreplication__plugin-class.jar (55 source files) and running annotation processors (AutoAnnotationProcessor, AutoValueProcessor) failed (Exit 1)
> > > > > plugins/replication/src/main/java/com/googlesource/gerrit/plugins/replication/AdminApi.java:17: error: package com.google.gerrit.entities does not exist
> > > > > import com.google.gerrit.entities.Project;
> > > > >                                  ^
> > > > 
> > > > Your gerrit workspace is inconsistent: gerrit-core and plugins don't match. You are missing this change in gerrit core: [1]. Try this in gerrit tree:
> ...
> > > > * [1] https://gerrit-review.googlesource.com/c/gerrit/+/225845
> > > 
> > > Shouldn't this change pin the plugin to a specific version of gerrit?
> > 
> > This change pinned the replication plugin to e5881ace0e39fdd15a3ce42d1626ebaf62595cbf: [2]. Note, that: [1] modified 1094 files, but only 200 are shown on the new UI (show all 1094 files would expand the file list and show all files).
> > 
> > [2] https://gerrit-review.googlesource.com/c/gerrit/+/225845/10/plugins/replication
> 
> So I'm still confused, if the plugin is pinned now, then why do I need to update my gerrit tree? Does the pinning only take effect when building out of tree? Is it possible to build replication plugin out of tree?

The plugin was pinned by the core change which renamed the package.

If you're working on the replication plugin and you've pulled the latest master branch of it, then you also need to pull the latest master branch of core gerrit.

Patch-set: 8