Update patch set 8
Patch Set 8:

> Patch Set 8:
> 
> Many errors like the following:
> 
> ERROR: /local/mnt/workspace/mfick/gerrit/gerrit.google2/plugins/replication/BUILD:5:1: Building plugins/replication/libreplication__plugin-class.jar (55 source files) and running annotation processors (AutoAnnotationProcessor, AutoValueProcessor) failed (Exit 1)
> plugins/replication/src/main/java/com/googlesource/gerrit/plugins/replication/AdminApi.java:17: error: package com.google.gerrit.entities does not exist
> import com.google.gerrit.entities.Project;
>                                  ^

Your gerrit workspace is inconsistent: gerrit-core and plugins don't match. You are missing this change in gerrit core: [1]. Try this in gerrit tree:

  $ cd gerrit
  $ git pull -r
  $ git submodule update
  $ git describe
  v3.0.3-3406-gd13a49041c

Now the build of replication plugin (and :release) works:

  $ bazel build plugins/replication
  INFO: Deleting stale sandbox base /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/sandbox
Target //plugins/replication:replication up-to-date:
  bazel-bin/plugins/replication/replication.jar
INFO: Elapsed time: 16.765s, Critical Path: 2.10s
INFO: 55 processes: 53 remote cache hit, 2 linux-sandbox.
INFO: Build completed successfully, 59 total actions

* [1] https://gerrit-review.googlesource.com/c/gerrit/+/225845

Patch-set: 8