GerritSshApi: strip 'gerrit+' instead of leaving only it
[2018-04-12 22:30:04,038] [ReplicateTo-bitbucket-1] ERROR com.googlesource.gerrit.plugins.replication.GerritSshApi : Error creating remote repository at gerrit+ssh://gerrit-bitbucket@localhost/:
Exception: org.eclipse.jgit.errors.TransportException: gerrit+: host must not be null.
Command: gerrit create-project --branch refs/heads/master repo/test
Output:
org.eclipse.jgit.errors.TransportException: gerrit+: host must not be null.

Change-Id: Ib53258625b3677f621d2e7e9d6df4b04a94a921d
Signed-off-by: Alon Bar-Lev <alon.barlev@gmail.com>