Update patch set 6
Patch Set 6: Verified-1

(3 comments)

Breaks the integration tests:
$ bazel test plugins/replication:replication_tests
ERROR: /Users/lucamilanesio/gerrithub/gerrit/plugins/replication/BUILD:36:1: Building plugins/replication/libreplication_util.jar (3 source files) and running annotation processors (AutoAnnotationProcessor, AutoValueProcessor) failed (Exit 1)
plugins/replication/src/test/java/com/googlesource/gerrit/plugins/replication/ReplicationIT.java:402: error: cannot find symbol
    return tasksStorage.list().stream()
                       ^
  symbol:   method list()
  location: variable tasksStorage of type ReplicationTasksStorage

Patch-set: 6
Reviewer: Gerrit User 1006192 <1006192@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1